FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# people

API is used for people... this should be a longer description of the API

## People [/people]

We can write something here as well... it's about PEOPLE

### List All People [GET]

What we have her is a list of people without the paramters

+ Response 200 (application/json)

        [
            {
                "id": "1",
                "name": "Peter",
                "surname": "Swift"
            },
            {
                "id": "2",
                "name": "Marko",
                "surname": "Python"
            },
            {
                "id": "3",
                "name": "Maja",
                "surname": "Ruby"
            },
            {
                "id": "4",
                "name": "Maja",
                "surname": "Ruby"
            }
        ]


## Person [/person/{id}]

This is entity person... can be longer description but we are in a hurry.

### Person [GET]

Get information about this person.

+ Parameters
    + id: 1 (number, required) - Id of a post.
            
+ Response 200 (application/json)

        [
            {
                "id": "1",
                "name": "Peter",
                "surname": "Swift",
                "email":"peter@swift.net",
                "city":"San Francisco",
                "age":"23",
                "timestamp":"2015-04-25 13:57:36 +0700"
            }
        ]
### Create a New Person [POST]

You may create your own person, just need to post it.

+ Request (application/json)

        {
            "name": "Zoki",
            "surname": "Objective-C",
            "email":"zoki@objective-c.net",
            "city":"Ljubljana",
            "age":"44"
        }

+ Response 201 (application/json)

    + Body

            {
                "id": "99",
                "message" : "created"
            }
            
### Delete a Post [DELETE /person/{id}]

+ Parameters
    + id (string) ... Id of the post

+ Response 204